### PR TITLE
Adding responsive menu fixes

### PR DESCRIPTION
**Pull request by darickdang**
Fixing button and navigation inconsistencies on the responsive menu

### CODE REVIEW

**Comment by jhaaaa** [comment]
Oh my gosh - thank you for caring, @darickdang! 

I just looked at the preview in Chrome and this is what I see in the non-responsive menu:
image

**Comment by darickdang** [comment]
@jhaaaa Apologies! Will go and fix. Thought it was scoped to just responsive views.

**Comment by darickdang** [comment]
@jhaaaa Alright, fixed!

**Review by jhaaaa — APPROVED** [review]
It is a beaut! Thank you for your time and expertise on this, @darickdang!

**Pull request merged**
