### PR TITLE
Examples Page

### PR DESCRIPTION
**Pull request by fabriguespe**
Page to show case all the example apps, quickstarts and repos for developers.

- [Preview](https://junk-range-possible-git-examplespage-xmtp-labs.vercel.app/docs/build/get-started/examples)

### CODE REVIEW

**Comment by jhaaaa** [comment]
Thank you for this @fabriguespe! As discussed, I added some fuller text descriptions for each item on the Examples page. I hope they work for you! 

If you look at the descriptions of the items in the Quickstarts section - some of them are apps and some of them are code. Do you want to move the apps to the Example apps section and just leave the code items in the Quickstarts section? No pressure either way - just wanted to mention it!

Also, maybe you already intend to do this - but I wonder if now that you've provided this comprehensive page - we no longer need these pages? https://xmtp.org/docs/build/get-started/quickstarts and https://xmtp.org/docs/build/get-started/example-apps? What do you think?

**Comment by fabriguespe** [comment]
@jhaaaa Looks great! Yes, I was planning on removing both pages with this PR. I added now.

You are right many in the quickstart section were more apps than quickstarts. I have moved some, how do they look?

What about adding a description to each section title?

**Review by jhaaaa — APPROVED** [review]
Thank you for this, @fabriguespe! <3 this!

**Comment by fabriguespe** [comment]
Hey @darickdang ! Would love to double check with you how we are presenting the repo's lists below each tab. Here is a [preview](https://junk-range-possible-git-examplespage-xmtp-labs.vercel.app/docs/build/get-started/examples)

**Comment by darickdang** [comment]
@fabriguespe I added some light styling to the example links but I think we should be good for now!

**Comment by fabriguespe** [comment]
Thank you @darickdang! Looks much better.

>I have updated the code to use a general CSS class instead of <strong> for convenience. Had to do a new PR because there were some issues with the CSS syntax in production. https://github.com/xmtp/xmtp-dot-org/pull/660

**Pull request merged**
