### PR TITLE
Added 2 new projects for BWX(Built with XMTP) page

### PR DESCRIPTION
**Pull request by richbustos**
### What?
Added two new projects that wanted to be added to the **Built With XMTP** page. 

Projects added:
1. Plex
2. Atticc

Screen Shot 2023-01-18 at 3 19 27 PM

### CODE REVIEW

**Comment by jhaaaa** [comment]
Love this so much, @richbustos - thank you for nurturing the growth of this page!

I think we need to shorten the description text for Plex just a bit so it doesn't wrap to four lines:

Mobile:
image

Desktop: It truncates with an `...`, and this is totally nitpicking, but there is a bit of text that peeks through from the fourth line:
image

If helpful, you can use this shortened text:

>Plex allows brands to query relevant audiences and understand who they are based on on- and off-chain attributes.

Removed the XMTP messaging piece as one might assume that messaging is included since they're listed on this page. Just an idea for what we might cut out to make the text fit!

One last thought - wondering what we think of alphabetizing the projects so that it doesn't imply that we're promoting one app more than another?

**Review by jhaaaa — DISMISSED** [review]
Thank you for this, @richbustos - left a few comments for your consideration!

**Comment by richbustos** [comment]
Thanks @jhaaaa for the review! Totally missed that as I just copied the text from the google form. Will update!

**Comment by richbustos** [comment]
Screen Shot 2023-01-19 at 12 42 55 PM

**Review by jhaaaa — APPROVED** [review]
Restarted the Cloudflare build and it worked - the earlier build error was just a hiccup? Reapproving and I think you should be good to merge!

**Comment by yash-luna** [comment]
❤️ - thanks for this Rich!

I'm down to alphabetize. Also, I wasn't able to try out Atticc because it requires an NFT. Were you @richbustos? Are we comfortable promoting apps that we haven't tried?

Also, should we add these to awesome-xmtp as well, since awesome-xmtp is a superset of all XMTP projects?

**Comment by richbustos** [comment]
@yash-luna Just tested Attic. Waiting on there reply to get on their allowlist.

**Comment by richbustos** [comment]
Tested both apps. Both are G2G!

**Pull request merged**
